name: fuodz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.2+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.2.0
  awesome_notifications: ^0.0.6+9
  basic_utils: ^3.3.3
  cached_network_image: ^3.0.0
  contained_tab_bar_view: ^0.7.1
  cool_alert: ^1.0.3
  country_picker: ^2.0.6
  cupertino_icons: ^1.0.0
  dartx: ^0.7.1
  dio: ^4.0.0
  dio_http_cache_lts: ^0.4.0
  dot_navigation_bar: ^0.1.1
  dotted_border: ^2.0.0
  dotted_line: ^2.0.2
  double_back_to_close: ^2.0.0
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3
  flag: ^3.1.0
  flutter:
    sdk: flutter
  flutter_fgbg: ^0.1.0
  flutter_icons: ^1.0.0+1
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_onboard: ^1.0.3
  flutter_rating_bar: ^4.0.0
  flutter_staggered_animations: ^0.1.2
  flutter_webview_plugin:
  fluttertoast: ^8.0.8
  geocoder:
  georange: ^1.0.0
  google_fonts: ^2.1.0
  google_map_location_picker:
  google_maps_flutter: ^2.0.6
  google_nav_bar: ^5.0.3
  i18n_extension: ^4.0.0
  image_picker: ^0.8.1+4
  in_app_review: ^2.0.2
  inspection: ^0.0.12
  jiffy: ^3.0.1
  line_icons: ^0.2.0
  location:
  map_launcher: ^1.1.2
  measure_size: ^2.0.0
  package_info: ^2.0.2
  pin_code_fields: ^6.1.0
  pretty_dio_logger: ^1.1.1
  provider: ^5.0.0
  pull_to_refresh:
  qr_code_scanner: ^0.4.0
  random_string: ^2.1.0
  rolling_switch: ^0.0.2
  schedulers: ^0.3.1
  shared_preferences: ^2.0.6
  singleton: ^0.0.2
  sliding_up_panel: ^2.0.0+1
  stacked: ^1.7.6
  sticky_headers: ^0.1.8+1
  supercharged: ^2.0.0
  circular_countdown_timer: ^0.2.0
  swipebuttonflutter: ^1.0.0
  ticketview: ^1.0.0
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0

dependency_overrides:
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  args: ^2.0.0
  firebase_chat: ^0.0.4
  cloud_firestore: ^1.0.3
  flutter_application_id: ^1.0.0
  flutter_polyline_points: ^0.2.4
  yaml: ^3.1.0
  equatable: ^2.0.0
  rxdart: ^0.27.1
  assets_audio_player: ^3.0.3+6
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_application_id: "^1.0.0"
  flutter_launcher_icons: "^0.9.0"
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
